# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: tomaszbednarz/al-folio-researcher:slim
    #build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
